import { HttpClient } from '@angular/common/http';
import { AfterViewInit, Component, ViewChild} from '@angular/core';
import {MatPaginator} from '@angular/material/paginator';
import {MatSort} from '@angular/material/sort';
import {merge, Observable, of as observableOf} from 'rxjs';
import {catchError, map, startWith, switchMap} from 'rxjs/operators';


@Component({
  selector: 'app-runhistory',
  templateUrl: './runhistory.component.html',
  styleUrls: ['./runhistory.component.css']
})
export class RunhistoryComponent implements AfterViewInit {
  //Mark RunID autogenerated vakue for backend perpose
  displayedColumns: string[] = ['Seq','RunId','Name','RunBy','ExecutionDateTime','Duration','Status'];
  data = ELEMENT_DATA;

  resultsLength = 2;
  isLoadingResults = false;
  isRateLimitReached = false;

  @ViewChild(MatPaginator) paginator: MatPaginator;
  @ViewChild(MatSort) sort: MatSort;

  ngAfterViewInit(): void {
  }

  pagetitle="Run History";

}

export interface RunHistory {
  seq: number;
  runId: number;
  name: string;
  runBy:string;
  executionDateTime:string;
  duration:string;
  status:string;
}

const ELEMENT_DATA: RunHistory[] = [
{seq:1,runId:123,name:'Run_Name'+new Date().toLocaleDateString(),runBy:'User',executionDateTime:new Date().toLocaleDateString(),duration:'20 Min',status:'Passed'},
{seq:2,runId:124,name:'Run_Name'+new Date().toLocaleDateString(),runBy:'User',executionDateTime:new Date().toLocaleDateString(),duration:'20 Min',status:'Passed'},
{seq:3,runId:125,name:'Run_Name'+new Date().toLocaleDateString(),runBy:'User',executionDateTime:new Date().toLocaleDateString(),duration:'20 Min',status:'Failed'},
{seq:4,runId:126,name:'Run_Name'+new Date().toLocaleDateString(),runBy:'User',executionDateTime:new Date().toLocaleDateString(),duration:'20 Min',status:'Passed'},
{seq:5,runId:123,name:'Run_Name'+new Date().toLocaleDateString(),runBy:'User',executionDateTime:new Date().toLocaleDateString(),duration:'20 Min',status:'Passed'},
{seq:6,runId:124,name:'Run_Name'+new Date().toLocaleDateString(),runBy:'User',executionDateTime:new Date().toLocaleDateString(),duration:'20 Min',status:'Passed'},
{seq:7,runId:125,name:'Run_Name'+new Date().toLocaleDateString(),runBy:'User',executionDateTime:new Date().toLocaleDateString(),duration:'20 Min',status:'Failed'}

];
